ko =
  signIn: "점주 로그인"
  signin: "점주 로그인"
  signOut: "로그아웃"
  signUp: "점주 가입"
  OR: "또는"
  forgotPassword: "비밀번호를 잊어버렸습니까?"
  emailAddress: "이메일"
  emailResetLink: "이메일 재설정 주소"
  dontHaveAnAccount: "아직 계정이 없습니까?"
  resetYourPassword: "비밀번호 재설정"
  updateYourPassword: "비밀번호 변경"
  password: "비밀번호"
  usernameOrEmail: "이름 또는 이메일"
  email: "이메일"
  ifYouAlreadyHaveAnAccount: "이미 계정이 있다면"
  signUpWithYourEmailAddress: "이메일 주소로 회원 가입"
  username: "이름"
  optional: "선택"
  signupCode: "가입 코드"
  clickAgree: "By clicking Register, you agree to our"
  privacyPolicy: "이용 약관"
  terms: "사용 계약"
  sign: "Sign"
  configure: "설정하기"
  with: "으로"
  createAccount: "Create an Account"
  verificationPending: "Confirm your email address"
  verificationPendingDetails: "A confirmation email has been sent to the email address you provided. Click on the confirmation link in the email to activate your account."
  and: "와"
  "Match failed":  "Match failed"
  "User not found":  "사용자 없음"

  error:
    minChar: "비밀번호는 7자 이상이어야 합니다"
    pwOneLetter: "Password requires 1 letter."
    pwOneDigit: "Password must have at least one digit."
    usernameRequired: "Username is required."
    emailRequired: "Email is required."
    signupCodeRequired: "Registration code is required."
    signupCodeIncorrect: "Registration code is incorrect."
    signInRequired: "You must be signed in to do that."
    usernameIsEmail: "Username cannot be an email address."

T9n.map "ko", ko
